# Interactive zshrc

# Extended globbing
setopt extended_glob
# zsh: exit 1 stylee stuff
setopt print_exit_value
# turn off annoying vim style tab completion
setopt no_auto_menu
# Enable partial list style completion
zstyle ':completion:*' list-suffixes true
# Bash-style null glob result -> no error
setopt null_glob
# Comments in the shell prompt are permitted
setopt interactivecomments

# Emacs keybindings
bindkey -e

for F in "$XDG_CONFIG_HOME"/zsh/rc.d/*; do
  source $F
done

# source $RESDIR/zsh/z-s-h/zsh-syntax-highlighting.zsh
